openapi: 3.0.0
components:
  schemas:
    Permission:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the permission
          example: 1
        name:
          type: string
          description: Permission's name (must be unique)
          example: "READ_USERS"
        description:
          type: string
          description: Permission's description
          example: "Permission to read user data"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the permission was created
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the permission was last updated
          example: "2024-01-15T10:30:00Z"
        deleted:
          type: boolean
          description: Soft delete flag (true if permission is deleted)
          example: false
      required:
        - id
        - name
        - description
        - createdAt
        - updatedAt
        - deleted

    CreatePermissionRequest:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 50
          description: Permission's name (must be unique)
          example: "DELETE_USERS"
        description:
          type: string
          minLength: 5
          maxLength: 255
          description: Permission's description
          example: "Permission to delete user accounts"

    UpdatePermissionRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 50
          description: Permission's name (must be unique if provided)
          example: "MANAGE_USERS"
        description:
          type: string
          minLength: 5
          maxLength: 255
          description: Permission's description
          example: "Permission to manage user accounts with full access"

    BulkDeletePermissionRequest:
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          items:
            type: integer
            minimum: 1
          minItems: 1
          maxItems: 100
          description: Array of permission IDs to delete
          example: [1, 2, 3]

    PermissionListResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
          example: true
        message:
          type: string
          description: Response message
          example: "Permissions fetched successfully"
        data:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/Permission"
            total:
              type: integer
              description: Total number of permissions
              example: 100
            page:
              type: integer
              description: Current page number
              example: 1
            limit:
              type: integer
              description: Number of items per page
              example: 10
            totalPages:
              type: integer
              description: Total number of pages
              example: 10

    PermissionResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
          example: true
        message:
          type: string
          description: Response message
          example: "Permission fetched successfully"
        data:
          $ref: "#/components/schemas/Permission"

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
          example: 400
        message:
          type: string
          description: Error message
          example: "Invalid request parameters"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                description: Field that caused the error
                example: "name"
              message:
                type: string
                description: Error message for the field
                example: "Permission name is required"
