services:
  - type: web
    name: sazonarte-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build && npm run prisma:generate
    startCommand: cd dist && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sazonarte-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: "*"
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: sazonarte-db
    databaseName: sazonarte-db
    user: sazonarte
    plan: free
