openapi: 3.0.0
paths:
  /permissions:
    get:
      tags:
        - Permissions
      summary: Get all permissions with pagination
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        200:
          description: Permissions fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermissionListResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: Permission not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /permissions/{id}:
    get:
      tags:
        - Permissions
      summary: Get a permission by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Permission ID
      responses:
        200:
          description: Permission fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermissionResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: Permission not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
