openapi: 3.0.0
paths:
  /permissions/{id}:
    patch:
      tags:
        - Permissions
      summary: Update a permission by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Permission ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePermissionRequest"
      responses:
        200:
          description: Permission updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermissionResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: Permission not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        409:
          description: Conflict - Permission with this name already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse" 