openapi: 3.0.0
paths:
  /permissions:
    post:
      tags:
        - Permissions
      summary: Create a new permission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePermissionRequest"
      responses:
        201:
          description: Permission created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PermissionResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        409:
          description: Conflict - Permission with this name already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse" 