openapi: 3.0.0
components:
  schemas:
    CreateItemRequest:
      type: object
      required:
        - name
        - description
        - categoryId
        - price
        - isExtra
        - isAvailable
        - imageUrl
      properties:
        name:
          type: string
          description: Item's name
          example: "Spaghetti"
        description:
          type: string
          description: Item's description
          example: "Classic pasta with meat sauce."
        categoryId:
          type: integer
          description: ID of the category this item belongs to
          example: 1
        price:
          type: number
          format: float
          description: Price of the item
          example: 12000
        isExtra:
          type: boolean
          description: Whether the item is an extra
          example: false
        isAvailable:
          type: boolean
          description: Whether the item is available
          example: true
        imageUrl:
          type: string
          description: URL of the item's image
          example: "https://example.com/images/spaghetti.jpg"

    MenuItemResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
          example: true
        message:
          type: string
          description: Response message
          example: "Item created successfully"
        data:
          $ref: "#/components/schemas/MenuItem"

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
          example: 400
        message:
          type: string
          description: Error message
          example: "Invalid request parameters"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                description: Field that caused the error
                example: "name"
              message:
                type: string
                description: Error message for the field
                example: "Name must be at least 3 characters long"
