openapi: 3.0.0
components:
  schemas:
    CreateMenuCategoryRequest:
      type: object
      required:
        - name
        - order
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 100
          description: Category's name (3-100 characters)
          example: "Main Dishes"
        description:
          type: string
          minLength: 1
          maxLength: 500
          description: Category's description (1-500 characters, optional)
          example: "Main course dishes"
        order:
          type: integer
          minimum: 0
          maximum: 999
          description: Display order of the category (0-999)
          example: 1

    MenuCategoryListResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
          example: true
        message:
          type: string
          description: Response message
          example: "Menu Categories fetched successfully"
        data:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/MenuCategory"
            total:
              type: integer
              description: Total number of categories
              example: 100
            page:
              type: integer
              description: Current page number
              example: 1
            limit:
              type: integer
              description: Number of items per page
              example: 10
            totalPages:
              type: integer
              description: Total number of pages
              example: 10

    MenuCategoryResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
          example: true
        message:
          type: string
          description: Response message
          example: "Menu Category created successfully"
        data:
          $ref: "#/components/schemas/MenuCategory"

    UpdateMenuCategoryRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 100
          description: Category's name (3-100 characters)
          example: "Main Dishes"
        description:
          type: string
          minLength: 1
          maxLength: 500
          description: Category's description (1-500 characters)
          example: "Main course dishes"
        order:
          type: integer
          minimum: 0
          maximum: 999
          description: Display order of the category (0-999)
          example: 1

    BulkDeleteMenuCategoryRequest:
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          minItems: 1
          maxItems: 100
          items:
            type: integer
            minimum: 1
          description: Array of category IDs to delete (1-100 IDs)
          example: [1, 2, 3, 4, 5]

    BulkDeleteMenuCategoryResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
          example: true
        message:
          type: string
          description: Response message with count of deleted categories
          example: "3 Menu Categories deleted successfully"
        data:
          type: object
          properties:
            deletedCount:
              type: integer
              description: Number of categories successfully deleted
              example: 3

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
          example: 400
        message:
          type: string
          description: Error message
          example: "Invalid request parameters"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                description: Field that caused the error
                example: "name"
              message:
                type: string
                description: Error message for the field
                example: "Name must be at least 3 characters long"
