openapi: 3.0.0
paths:
  /roles/{id}:
    delete:
      tags:
        - Roles
      summary: Delete a role by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Role ID
      responses:
        200:
          description: Role deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Role with ID {id} has been deleted successfully"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: Role not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
