openapi: 3.0.0
paths:
  /roles:
    post:
      tags:
        - Roles
      summary: Create a new role for users
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRoleRequest"
      responses:
        201:
          description: Role created successfully
        409:
          description: Conflict.
        400:
          description: Bad Request
