openapi: 3.0.0
paths:
  /roles/search:
    get:
      tags:
        - Roles
      summary: Search roles with filtering and pagination
      description: |
        Search for roles by name and filter by active status.
        Supports pagination and case-insensitive name search.
      parameters:
        - in: query
          name: search
          schema:
            type: string
            minLength: 1
            maxLength: 100
          description: Search term for filtering roles by name (case-insensitive)
          example: "admin"
        - in: query
          name: active
          schema:
            type: string
            enum: ["true", "false"]
          description: Filter roles by active status
          example: "true"
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
          example: 1
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
          description: Number of items per page
          example: 20
      responses:
        200:
          description: Roles search completed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoleListResponse"
              example:
                success: true
                message: "Roles search completed successfully"
                data:
                  items:
                    - id: 1
                      name: "ADMIN"
                      description: "Administrator role with full access"
                      createdAt: "2024-01-15T10:30:00Z"
                      updatedAt: "2024-01-15T10:30:00Z"
                      deleted: false
                    - id: 3
                      name: "MODERATOR"
                      description: "Moderator role with limited access"
                      createdAt: "2024-01-15T11:00:00Z"
                      updatedAt: "2024-01-15T11:00:00Z"
                      deleted: false
                  total: 2
                  page: 1
                  limit: 20
                  totalPages: 1
        400:
          description: Bad Request - Invalid search parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                status: 400
                message: "Invalid search parameters"
                errors:
                  - field: "search"
                    message: "Search term must be at least 1 character"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse" 