openapi: 3.0.0
paths:
  /tables/{id}/status:
    patch:
      tags:
        - Tables
      summary: Update table status
      description: |
        Updates the status of a specific table (available/occupied/reserved/maintenance).
        This endpoint is commonly used for real-time table status management in
        restaurant operations.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: Table ID to update status
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTableStatusRequest"
            examples:
              setAvailable:
                summary: Set table as available
                value:
                  status: "AVAILABLE"
              setOccupied:
                summary: Set table as occupied
                value:
                  status: "OCCUPIED"
              setReserved:
                summary: Set table as needs cleaning state
                value:
                  status: "NEEDS_CLEANING"
      responses:
        200:
          description: Table status updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TableResponse"
              example:
                success: true
                message: "Table status updated successfully"
                data:
                  id: 1
                  number: "1"
                  status: "OCCUPIED"
                  location: "Window side"
                  description: "Table by the window with garden view"
                  createdAt: "2024-01-15T10:30:00Z"
                  updatedAt: "2024-01-15T12:30:00Z"
                  deleted: false
                  deletedAt: null
        400:
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                invalidStatus:
                  summary: Invalid status value
                  value:
                    success: false
                    message: "Invalid table status"
                    error: "BAD_REQUEST"
                missingStatus:
                  summary: Missing status field
                  value:
                    success: false
                    message: "Status is required"
                    error: "BAD_REQUEST"
        404:
          description: Table not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                success: false
                message: "Table not found"
                error: "NOT_FOUND"
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                success: false
                message: "Internal server error"
                error: "INTERNAL_SERVER_ERROR"
