openapi: 3.0.0
paths:
  /menus/categories:
    get:
      tags:
        - Menu Categories
      summary: Get all menu categories with pagination
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        200:
          description: Menu categories fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MenuCategoryListResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /menus/categories/{id}:
    get:
      tags:
        - Menu Categories
      summary: Get a menu categories by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Role ID
      responses:
        200:
          description: Menu category fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MenuCategoryResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: Menu Category not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
