openapi: 3.0.0
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        201:
          description: User registered successfully
        409:
          description: Conflict
        400:
          description: Bad Request

  /auth/login:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        200:
          description: User registered successfully
        401:
          description: Unauthorized
        400:
          description: Bad Request
