openapi: 3.0.0
components:
  schemas:
    Role:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the role
          example: 1
        name:
          type: string
          description: Role's name (must be unique)
          example: "ADMIN"
        description:
          type: string
          description: Role's description
          example: "Administrator role with full access"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the role was created
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the role was last updated
          example: "2024-01-15T10:30:00Z"
        deleted:
          type: boolean
          description: Soft delete flag (true if role is deleted)
          example: false
      required:
        - id
        - name
        - description
        - createdAt
        - updatedAt
        - deleted

    CreateRoleRequest:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 50
          description: Role's name (must be unique)
          example: "CASHIER"
        description:
          type: string
          minLength: 5
          maxLength: 200
          description: Role's description
          example: "Cashier role with limited administrative access"
        permissionIds:
          type: array
          items:
            type: integer
            minimum: 1
          description: Array of permission IDs to assign to the role
          example: [1, 2, 4]

    UpdateRoleRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 50
          description: Role's name (must be unique if provided)
          example: "WAITER"
        description:
          type: string
          minLength: 5
          maxLength: 200
          description: Role's description
          example: "Waiter role with access to orders and menus"
        permissionIds:
          type: array
          items:
            type: integer
            minimum: 1
          description: Array of permission IDs to assign to the role
          example: [4]

    BulkDeleteRoleRequest:
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          items:
            type: integer
            minimum: 1
          minItems: 1
          maxItems: 100
          description: Array of role IDs to delete
          example: [1, 2, 3]

    RoleListResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
          example: true
        message:
          type: string
          description: Response message
          example: "Roles fetched successfully"
        data:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/Role"
            total:
              type: integer
              description: Total number of roles
              example: 100
            page:
              type: integer
              description: Current page number
              example: 1
            limit:
              type: integer
              description: Number of items per page
              example: 10
            totalPages:
              type: integer
              description: Total number of pages
              example: 10

    RoleResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the request was successful
          example: true
        message:
          type: string
          description: Response message
          example: "Role fetched successfully"
        data:
          $ref: "#/components/schemas/Role"

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
          example: 400
        message:
          type: string
          description: Error message
          example: "Invalid request parameters"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                description: Field that caused the error
                example: "name"
              message:
                type: string
                description: Error message for the field
                example: "Role name is required"
