openapi: 3.0.0
paths:
  /menus/items:
    get:
      tags:
        - Menu Items
      summary: Get Menu Items
      description: Retrieve a paginated list of all menu items from the system. Supports pagination parameters for efficient data retrieval and display.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
          example: 1
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
          description: Number of items per page
          example: 10
      responses:
        200:
          description: Menu Items retrieved successfully
          content:
            application/json:
              schema:
                $ref: "./schemas/components.yaml#/components/schemas/MenuItemListResponse"
              examples:
                menuItemList:
                  summary: Successful response with paginated menu items
                  value:
                    success: true
                    message: "Menu Items fetched successfully"
                    data:
                      - id: 1
                        categoryId: 1
                        name: "Spaghetti"
                        description: "Classic pasta with meat sauce"
                        price: 12000
                        isExtra: false
                        isAvailable: true
                        imageUrl: "https://example.com/images/spaghetti.jpg"
                        createdAt: "2024-01-15T10:30:00Z"
                        updatedAt: "2024-01-15T10:30:00Z"
                      - id: 2
                        categoryId: 1
                        name: "Pizza Margherita"
                        description: "Traditional Italian pizza"
                        price: 15000
                        isExtra: false
                        isAvailable: true
                        imageUrl: "https://example.com/images/pizza.jpg"
                        createdAt: "2024-02-15T10:30:00Z"
                        updatedAt: "2024-02-15T10:30:00Z"
                    meta:
                      page: 1
                      limit: 10
                      total: 25
                      totalPages: 3
        400:
          description: Invalid pagination parameters
          content:
            application/json:
              schema:
                $ref: "./schemas/components.yaml#/components/schemas/ErrorResponse"
              example:
                success: false
                message: "Invalid pagination parameters"
                error: "BAD_REQUEST"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./schemas/components.yaml#/components/schemas/ErrorResponse"
